exports.DEVELOPER_HOME_SCREEN_ROUTE_NAME = "DEVELOPER_HOME";
exports.LOGIN_SCREEN_ROUTE_NAME = "LOGIN";
exports.REGISTRATION_SCREEN_ROUTE_NAME = "REGISTRATION";
exports.SPLASH_SCREEN_ROUTE_NAME = "SPLASH";
exports.EMPTY_TEXT = "";
exports.MEMBER_CATEGORY = "MEMBER";
exports.SOCIETY_CATEGORY = "SOCIETY";
exports.DEVELOPER_CATEGORY = "DEVELOPER";
